### DISCUSSION TITLE
Deployment errors

### DISCUSSION THREAD

**Discussion by clivewalkden** [MAD-I-T/magento-actions#44] [Q&A] [answered]
Hi all,

Just checking if this is happening to other people. During my issue #43 the deployment process was erroring but it didn't stop the process, it simply carried on to the next step and successfully completed with a broken site at the end. Is there a way for the deployer application to send the correct error to the GitHub action to halt the process or is it just me this is not working for?

Thanks, Clive

**Comment by seyuf** [comment]
Humm, surely there are conditions leading to the bypassing of failed jobs ?
E.g (`if: always()`): 
```     
    - name: 'launch security scanner files'
      if: always()
      uses: MAD-I-T/magento-actions@v3.16
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'security-scan-files'
        elasticsearch: 1
```
