### DISCUSSION TITLE
Error response from daemon: Head "https://ghcr.io/v2/mad-i-t/magento-actions/manifests/3.20

### DISCUSSION THREAD

**Discussion by alexandrosk** [MAD-I-T/magento-actions#48] [Q&A] [answered]
Anyone seen this before? what Im doing wrong? :D 

That's how it looks like 
```
name: m2-actions-test
on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 unit tests & build'
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.1.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: 'this step will build an magento artifact'
        uses: MAD-I-T/magento-actions@v3.20
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          composer_version: 2
          php: '8.1'
          process: 'build'
          elasticsearch: 1
```
