### ISSUE TITLE
Add pwa-studio installer

### ISSUE THREAD

**Issue by seyuf** [MAD-I-T/magento-actions#27]
Bootstrap a magento pwa-studio project through github-actions : 
 ```
  - name: 'install fresh pwa-studio project'
      uses: MAD-I-T/magento-actions@master
      with:
        process: 'pwa-studio-install'
        #no_push: 1    #uncomment this to prevent pushing the src code to the github repo usefull in cases where only tests are needed
  ```
