### ISSUE TITLE
Error on integration Test Magento 2.4.5

### ISSUE THREAD

**Issue by francesco-di-marcantonio** [MAD-I-T/magento-actions#36]
Hi this is the result when we run the integration test on a magento2.4.5

i cant find any reference for this error in magento.

Any suggestion?

```
Enabling caches:

In State.php line 213:

  [Magento\Framework\Exception\LocalizedException]
  Area code "frontend" does not exist


Exception trace:
  at /github/workspace/magento/vendor/magento/framework/App/State.php:213
 Magento\Framework\App\State->checkAreaCode() at /github/workspace/magento/vendor/magento/framework/App/State.php:133
 Magento\Framework\App\State->setAreaCode() at /github/workspace/magento/vendor/hyva-themes/magento2-theme-module/src/Model/HyvaModulesConfig.php:109
 Hyva\Theme\Model\HyvaModulesConfig->initFrontendArea() at /github/workspace/magento/vendor/hyva-themes/magento2-theme-module/src/Model/HyvaModulesConfig.php:102
 Hyva\Theme\Model\HyvaModulesConfig->createObjectManagerWithCurrentModulesList() at /github/workspace/magento/vendor/hyva-themes/magento2-theme-module/src/Model/HyvaModulesConfig.php:87
 Hyva\Theme\Model\HyvaModulesConfig->gatherConfigData() at /github/workspace/magento/vendor/hyva-themes/magento2-theme-module/src/Model/HyvaModulesConfig.php:51
 Hyva\Theme\Model\HyvaModulesConfig->getJson() at /github/workspace/magento/vendor/hyva-themes/magento2-theme-module/src/Model/HyvaModulesConfig.php:44
 Hyva\Theme\Model\HyvaModulesConfig->generateFile() at /github/workspace/magento/vendor/hyva-themes/magento2-theme-module/src/Plugin/HyvaModulesConfig/UpdateOnModuleStatusChange.php:40
 Hyva\Theme\Plugin\HyvaModulesConfig\UpdateOnModuleStatusChange->afterSaveConfig() at /github/workspace/magento/vendor/magento/framework/Interception/Interceptor.php:146
 Magento\Framework\App\DeploymentConfig\Writer\Interceptor->Magento\Framework\Interception\***closure***() at /github/workspace/magento/vendor/magento/framework/Interception/Interceptor.php:153
 Magento\Framework\App\DeploymentConfig\Writer\Interceptor->___callPlugins() at /github/workspace/magento/dev/tests/integration/tmp/sandbox-0-d773ce1a99a9bf5b8e2ac0f83a407f7b983d18ecd6acc5aeace3e6499b161009/generated/code/Magento/Framework/App/DeploymentConfig/Writer/Interceptor.php:32
 Magento\Framework\App\DeploymentConfig\Writer\Interceptor->saveConfig() at /github/workspace/magento/vendor/magento/framework/App/Cache/State.php:104
 Magento\Framework\App\Cache\State->persist() at /github/workspace/magento/vendor/magento/framework/App/Cache/Manager.php:77
 Magento\Framework\App\Cache\Manager->setEnabled() at /github/workspace/magento/setup/src/Magento/Setup/Model/Installer.php:1414
 Magento\Setup\Model\Installer->updateCaches() at n/a:n/a
 call_user_func_array() at /github/workspace/magento/setup/src/Magento/Setup/Model/Installer.php:386
 Magento\Setup\Model\Installer->install() at /github/workspace/magento/setup/src/Magento/Setup/Console/Command/InstallCommand.php:238
 Magento\Setup\Console\Command\InstallCommand->execute() at /github/workspace/magento/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /github/workspace/magento/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /github/workspace/magento/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /github/workspace/magento/vendor/magento/framework/Console/Cli.php:116
 Magento\Framework\Console\Cli->doRun() at /github/workspace/magento/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /github/workspace/magento/bin/magento:23
```
This is the file action:

```
name: m2-integration-test

on: [push]

jobs:
  magento2-integration-test:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 integration test'
    services:
      mysql:
        image: docker://mysql:8
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=magento -e MYSQL_USER=magento -e MYSQL_PASSWORD=magento -e MYSQL_DATABASE=magento --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
      elasticsearch:
        image: docker://elasticsearch:7.1.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      rabbitmq:
        image: docker://rabbitmq:3.8-alpine
        env:
          RABBITMQ_DEFAULT_USER: "magento"
          RABBITMQ_DEFAULT_PASS: "magento"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v3
      - name: 'launch magento2 integration test'
        uses: MAD-I-T/magento-actions@v3.15
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          php: '8.1'
          process: 'integration-test'
          elasticsearch: 1
          composer_version: 2

```

and this is the file mysql-config:

```
return [
    'db-host' => 'mysql',
    'db-user' => 'root',
    'db-password' => 'magento',
    'db-name' => 'magento',
    'db-prefix' => '',
    'backend-frontname' => 'backend',
    'admin-user' => \Magento\TestFramework\Bootstrap::ADMIN_NAME,
    'admin-password' => \Magento\TestFramework\Bootstrap::ADMIN_PASSWORD,
    'admin-email' => \Magento\TestFramework\Bootstrap::ADMIN_EMAIL,
    'admin-firstname' => \Magento\TestFramework\Bootstrap::ADMIN_FIRSTNAME,
    'admin-lastname' => \Magento\TestFramework\Bootstrap::ADMIN_LASTNAME,
    'amqp-host' => 'rabbitmq',
    'amqp-port' => '5672',
    'amqp-user' => 'magento',
    'amqp-password' => 'magento',
    'elasticsearch-host' => "elasticsearch",
    'elasticsearch-port' => "9200"
    ];

```

**Comment by seyuf** [comment]
Hi sir,
I just tried this and seems to be working fine?:

```
name: m2-actions-test
on: [push]

jobs:
  magento2-integration-test:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 integration test'
    services:
      mysql:
        image: docker://mysql:8
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=magento -e MYSQL_USER=magento -e MYSQL_PASSWORD=magento -e MYSQL_DATABASE=magento --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
      elasticsearch:
        image: docker://elasticsearch:7.1.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      rabbitmq:
        image: docker://rabbitmq:3.8-alpine
        env:
          RABBITMQ_DEFAULT_USER: "magento"
          RABBITMQ_DEFAULT_PASS: "magento"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - 5672:5672

    steps:
      - name: 'install fresh magento repo'
        #if: always()
        if: ${{true}}
        uses: MAD-I-T/magento-actions@master
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'create-project'
          magento_version: 2.4.5
          no_push: 1
      - name: 'launch magento2 integration test'
        if: ${{true}}
        uses: MAD-I-T/magento-actions@v3.15
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'integration-test'
          elasticsearch: 1
```

**Comment by francesco-di-marcantonio** [comment]
tryed this file but it ends with an error.
![Schermata del 2022-11-08 16-32-43](https://user-images.githubusercontent.com/98045367/200607843-f435425b-b55f-4ad3-9caa-6981d07d3085.png)
Any info?

**Comment by seyuf** [comment]
Yeah, magento integration tests, if you choose to do all of them, takes hours. So it is often killed by the actions after some time:  
You should have some network warning/error like the following in the summary section of the workflow:
```
The hosted runner: Hosted Agent lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

**Comment by seyuf** [comment]
https://www.integer-net.com/integration-tests-with-magento-2/

Just try and modify dev/tests/integration/phpunit.xml.dist ?

**Comment by francesco-di-marcantonio** [comment]
ah okey, isn't there an option to change the phpunit file? Thanks for support!

**Comment by seyuf** [comment]
Humm you mean ? Something like ```dev/tests/integration/phpunit.xml``` ? instead? No but you're welcome to open a new issue for that feature. 
By the way, you can override  the ***integration-test-config\*.php*** files in the config dir through the [override_settings](https://forum.madit.fr/t/magento-actions-override-default-scripts/19) flag

**Comment by seyuf** [comment]
Reopening this @bluerain-1 Update the doc for the posterity.

**Comment by seyuf** [comment]
Added support for auto selection of `dev/tests/integration/phpunit.xml` instead of `dev/tests/integration/phpunit.xm.dist` if exists. As well as **testsuite**, **filter** and **test class path** options, e.g below : 

```
      - name: 'integration test by custom testsuite name'
        if: ${{true}}
        uses: MAD-I-T/magento-actions@master
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'integration-test'
          elasticsearch: 1
          testsuite: "Memory Usage Tests"
      
      - name: 'integration test class'
        if: ${{true}}
        uses: MAD-I-T/magento-actions@master
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'integration-test'
          elasticsearch: 1
          integration_class: "./testsuite/Magento/MemoryUsageTest.php"

      - name: 'integration test class filter'
        if: ${{true}}
        uses: MAD-I-T/magento-actions@master
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'integration-test'
          elasticsearch: 1
          integration_class: "./testsuite/Magento/MemoryUsageTest.php"
          integration_filter: "testAppReinitializationNoMemoryLeak"
```
