### ISSUE TITLE
Installation error: You must be using the interactive console to authenticate

### ISSUE THREAD

**Issue by leoner-omnipro** [MAD-I-T/magento-actions#41]
Hello!
I'm new using actions for my projects and I'm trying to use `unit-test` action, when install process of composer starts it fails with this error for some packages
```shell
Error: The 'https://repo.magento.com/archives/magento/composer-dependency-version-audit-plugin/magento-composer-dependency-version-audit-plugin-0.1.1.0.zip' URL required authentication (HTTP 401).
You must be using the interactive console to authenticate
In AuthHelper.php line 197:

Error: The 'https://repo.magento.com/archives/magento/module-variable/magento-module-variable-100.4.3.0.zip' URL required authentication (HTTP 401).
You must be using the interactive console to authenticate
In AuthHelper.php line 197:
```

Any way to get help?
Here the workflow
```yml
jobs:
  build-test:
    name: PHPUnit
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@master

      - name: 'This step will execute all the unit tests available'
        uses: MAD-I-T/magento-actions@v3.16
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        with:
          process: 'unit-test'
          php: 8.1
          magento_version: 2.4.5-p1
          testsuite: 'Unit_Tests_App_Code'
          unit_test_config: 'dev/tests/unit/phpunit.xml'
          override_settings: 1
          elasticsearch: 1
```

and the bash file
```bash
#!/usr/bin/env bash

#set -e

PROJECT_PATH="$(pwd)"

echo "currently in $PROJECT_PATH"

cd "$PROJECT_PATH" || exit

/usr/local/bin/composer install --prefer-dist --no-progress
chmod +x bin/magento

bin/magento setup:install --admin-firstname="local" --admin-lastname="local" --admin-email="local@omni.pro" --admin-user="local" --admin-password="local123" --base-url="http://magento.build/" --backend-frontname="admin" --db-host="mysql" --db-name="magento" --db-user="root" --db-password="magento" --use-secure=0 --use-rewrites=1 --use-secure-admin=0 --session-save="db" --currency="COP" --language="es_CO" --timezone="America/Bogota" --cleanup-database --skip-db-validation --elasticsearch-host="elasticsearch" --elasticsearch-port=9200

if [ ! -d "$PROJECT_PATH/vendor/bin" ]; then
    echo "Installing composer dependencies"
    /usr/local/bin/composer install --prefer-dist --no-progress

    echo "Running unit tests"

    cd "$PROJECT_PATH/vendor/bin" || exit
    ./phpunit ./vendor/bin/phpunit -c "$PROJECT_PATH/dev/tests/unit/phpunit.xml" --testsuite "Unit_Tests_App_Code"
fi

echo "exit-code is $? - ${EXIT_CODE}"
```
Thanks!

**Comment by seyuf** [comment]
Hi,

The issue is certainly coming from your overrided unit test file ? 
Can you tell me why are you overriding? The default behaviour should be largely enough?
A quick look at the file, i can isolate some issues for example [unit testing on magento](https://developer.adobe.com/commerce/testing/guide/unit/command-line/) does not have a testsuite param. That is for integration tests.
At the moment, only `unit_test_config ` and `unit_test_subset_path ` are available.
Please read the documentation linked above and let me know, if i misunderstood what you're trying to do.

Regards

Also you can check the tutorial on our forum : https://forum.madit.fr/t/unit-testing-in-magento-2/16/4

**Comment by seyuf** [comment]
Also do not forget to configure the mysql and elasticsearch services as follows:

```
jobs:
  magento2-build:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 tests & build'
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.1.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
```

**Comment by seyuf** [comment]
Also use the step to install magento before running the unit testing. If there is no magento src on your project : 

```
...
steps:
      - uses: actions/checkout@v2

      - name: 'install fresh magento repo'
        if: ${{true}}
        uses: MAD-I-T/magento-actions@v3.10
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'create-project'
          magento_version: 2.4.4
          no_push: 1   ## add this arg to not push to the repo ideal for quick test on specific version
          
      - name: 'launch magento2 unit test'
        uses: MAD-I-T/magento-actions@master
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'unit-test'
          unit_test_config: 'dev/tests/unit/phpunit.xml.dist'
          unit_test_subset_path: '../Madit/Sips2'
          elasticsearch: 1

```
See full example [here](https://github.com/MAD-I-T/magento-worldline-sips2/blob/master/.github/workflows/main.yml)

**Comment by leoner-omnipro** [comment]
> Hi,
> 
> The issue is certainly coming from your overrided unit test file ? Can you tell me why are you overriding? The default behaviour should be largely enough? A quick look at the file, i can isolate some issues for example [unit testing on magento](https://developer.adobe.com/commerce/testing/guide/unit/command-line/) does not have a testsuite param. That is for integration tests. At the moment, only `unit_test_config ` and `unit_test_subset_path ` are available. Please read the documentation linked above and let me know, if i misunderstood what you're trying to do.
> 
> Regards
> 
> Also you can check the tutorial on our forum : https://forum.madit.fr/t/unit-testing-in-magento-2/16/4

Hello, 
We override the file because we have many vendors in our project and we only want to run tests for our own modules. Testsuite param is available for phpunit refs: [Composing a Test Suite Using XML Configuration](https://phpunit.readthedocs.io/en/9.5/organizing-tests.html#composing-a-test-suite-using-xml-configuration)
Custom testsuites are created with this propose of run individual suites.

**Comment by leoner-omnipro** [comment]
> Also use the step to install magento before running the unit testing. **If there is no magento src on your project** (meaning no magento dir in your github repo) :
> 
> ```
> ...
> steps:
>       - uses: actions/checkout@v2
> 
>       - name: 'install fresh magento repo'
>         if: ${{true}}
>         uses: MAD-I-T/magento-actions@v3.10
>         env:
>           COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
>         with:
>           process: 'create-project'
>           magento_version: 2.4.4
>           no_push: 1   ## add this arg to not push to the repo ideal for quick test on specific version
>           
>       - name: 'launch magento2 unit test'
>         uses: MAD-I-T/magento-actions@master
>         env:
>           COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
>         with:
>           process: 'unit-test'
>           unit_test_config: 'dev/tests/unit/phpunit.xml.dist'
>           unit_test_subset_path: '../Madit/Sips2'
>           elasticsearch: 1
> ```
> 
> See full example [here](https://github.com/MAD-I-T/magento-worldline-sips2/blob/master/.github/workflows/main.yml)

Is strictly necessary?
this is our project structure for Magento EE
![image](https://user-images.githubusercontent.com/93623882/204840038-a865a9eb-4752-4034-9278-b8b6fef9c224.png)

Modules that we want to test are in the `app/code` folder following magento structure for custom extensions

**Comment by seyuf** [comment]
Yep, i meant for this actions exclusively. 
The testsuite is not available because the latter is primarily designed for magento2.
Feel free to open a new issue, if you want that feature added as we already have the argument available for integration tests. We'll take a look at it.
As for your use case ok. So as mentioned above check the existence or use the install step to install the source first. 
You can see similar use case here (https://github.com/MAD-I-T/magento-worldline-sips2/blob/master/.github/workflows/main.yml)

**Comment by seyuf** [comment]
> > Also use the step to install magento before running the unit testing. **If there is no magento src on your project** (meaning no magento dir in your github repo) :
> > ```
> > ...
> > steps:
> >       - uses: actions/checkout@v2
> > 
> >       - name: 'install fresh magento repo'
> >         if: ${{true}}
> >         uses: MAD-I-T/magento-actions@v3.10
> >         env:
> >           COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
> >         with:
> >           process: 'create-project'
> >           magento_version: 2.4.4
> >           no_push: 1   ## add this arg to not push to the repo ideal for quick test on specific version
> >           
> >       - name: 'launch magento2 unit test'
> >         uses: MAD-I-T/magento-actions@master
> >         env:
> >           COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
> >         with:
> >           process: 'unit-test'
> >           unit_test_config: 'dev/tests/unit/phpunit.xml.dist'
> >           unit_test_subset_path: '../Madit/Sips2'
> >           elasticsearch: 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > See full example [here](https://github.com/MAD-I-T/magento-worldline-sips2/blob/master/.github/workflows/main.yml)
> 
> Is strictly necessary? this is our project structure for Magento EE ![image](https://user-images.githubusercontent.com/93623882/204840038-a865a9eb-4752-4034-9278-b8b6fef9c224.png)
> 
> Modules that we want to test are in the `app/code` folder following magento structure for custom extensions

In you case, you'll need to move all your magento files in to a directory called magento at the root of your repo.
If you don't want to do that you'll indeed need the install step first (with the no_push arg to 1).

**Comment by leoner-omnipro** [comment]
> In you case, you'll need to move all your magento files in to a directory called magento at the root of your repo. If you don't want to do that you'll indeed need the install step first (with the no_push arg to 1).

Is weird that I'll have to do that, because we're using the same structure for `phpcs-test`  action with this config
```yml
magento2-code-sniffer:
        name: Code standards analysis
        if: contains(github.event.pull_request.labels.*.name, 'area:backend')
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: "⚖️ Start standards testing"
              if: always()
              uses: MAD-I-T/magento-actions@v3.15
              env:
                  COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
              with:
                  process: "phpcs-test"
                  extension: "Omnipro"
                  severity: 4
                  php: 8.1
                  standard: Magento2
                  magento_version: 2.4.5-p1
                  override_settings: 1
            - run: echo "✅ Static testing finished"
```

and this script
```bash
#!/usr/bin/env bash
PROJECT_PATH="$(pwd)"
CODING_STANDARD_PATH="vendor/magento/magento-coding-standard"

echo "currently in $PROJECT_PATH"

if [ -d "$CODING_STANDARD_PATH" ]; then
  rm -rf "$CODING_STANDARD_PATH"
fi

echo "#====== Installing Magento Coding Standard ======#"

composer create-project magento/magento-coding-standard --stability=dev "$PROJECT_PATH/$CODING_STANDARD_PATH"

cd "$PROJECT_PATH/$CODING_STANDARD_PATH" || exit

echo "#====== Running PHP Code Sniffer ======#"

echo "Path to analyze: $PROJECT_PATH/app/code/$INPUT_EXTENSION"

if [ -d "$PROJECT_PATH/app/code/$INPUT_EXTENSION" ]; then
    echo "Analyzing $PROJECT_PATH/app/code/$INPUT_EXTENSION"
    vendor/bin/phpcs --standard="$INPUT_STANDARD" --severity="${INPUT_SEVERITY:-1}" "$PROJECT_PATH/app/code/$INPUT_EXTENSION"
else
    echo "Error: Directory $PROJECT_PATH/app/code/$INPUT_EXTENSION does not exists."
    exit 1
fi
```

Actions works in different way?

**Comment by seyuf** [comment]
Yep this one works differently.

Also in the case, you choose the latter (the install step):

You'll have to adjust ```unit_test_config: 'dev/tests/unit/phpunit.xml'``` to ```unit_test_config: '../dev/tests/unit/phpunit.xml'```

**Comment by leoner-omnipro** [comment]
Okay, thank you for the suggestions, I'll try implement them and I could come here again if something new happen, ty!

**Comment by seyuf** [comment]
If you're not on magento cloud and if you can. It's best you simply refactor your project move the files in a magento dir at the root of your github. Or maybe we should handle cases like yours allow users specify the root magento dir? Even though i feel that's an overkill and not very clean, in the end.

**Comment by leoner-omnipro** [comment]
Indeed the project is oriented to be deployed in Magento cloud, we want to use these advantages that github actions have to make the deployment process cleaner. We found your repository and it was the only one that best suited the need because it is quite flexible and there are several things that can be customized with the scripts. It would be very helpful if you could give a focus to this kind of projects in Cloud.

**Comment by seyuf** [comment]
Humm, you seem to have gotten the gists of the project which is his flexibility. If you've understood the overriding process, which seems to be the case, you should be fine. As of now, we're mainly focused on the open source version (s). Maybe a bit too much as you mentioned ^^. We'll reaccess this point, in the near future.

**Comment by leoner-omnipro** [comment]
Thank you very much for your collaboration with this case 🚀

On the other hand, I have modified the action according to what you have suggested and based on the example, I still have not been able to perform a complete insertion of the process, now it is the following error
```bash
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mysql fail
| ed: Name or service not known
```

I also added the parameters of the services, to integrate in our case mariadb

```yml
    services:
      mysql:
        image: docker://mariadb:10.4
        env:
          MARIADB_ROOT_PASSWORD: magento
          MARIADB_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.17.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
```

I think it should work in the same way, shouldn't it?

**Comment by seyuf** [comment]
Hunn
Please provide the full workflow config. This can happen depending on the container. Try with:

```
build-test:
    name: PHPUnit
    runs-on: 'ubuntu-latest'
   container: ubuntu
   services:
     ....
```
Like in [here](https://github.com/MAD-I-T/magento-worldline-sips2/blob/05d5d1de2e666d68d70fea00600703aea0f5ad49/.github/workflows/main.yml#L8).
Supposing you're using some github shared-runner and not a selfhosted. 
Also for now let's stick to the mysql config. So we have the same setup. You can switch to mariadb afterward.

BTW if you're on a selfhosted the following should work : 
```
  magento2-build:
    runs-on: self-hosted
    name: 'm2 tests & build'
    services:
       ...
```

**Comment by seyuf** [comment]
@leoner-omnipro the latest version should now be able to cover unorthodox project scaffolding. I'll let you try and give some feedback?

In the meanwhile, i'm closing this. Feel free to reopen.

**Comment by leoner-omnipro** [comment]
Hey @seyuf! 👋🏽
We have recently tested the new update using version 3.18 and everything is working great with no issues. This suits our needs very well, thank you very much for this effort!

**Comment by seyuf** [comment]
Pleased to hear that.
Thank you for the suggestion. I'm sure it'll help others.
Best 🙏

**Comment by leoner-omnipro** [comment]
Hey @seyuf!
For some reason when we trying to use the "security-scan-files" action, it throws the next error
```bash
Error: The 'https://repo.magento.com/archives/magento/composer-root-update-plugin/magento-composer-root-update-plugin-2.0.3.0.zip' URL required authentication (HTTP 401).
```

and just happens with that module, what could we do to solve this issue?

Here the full action file if needed
```yml
name: M2Actions

on:
  push:
    branches:
      - '*'
      - '!staging'
      - '!production'
  pull_request:
    types: [ 'labeled', 'synchronize', 'ready_for_review' ]
    branches:
      - 'staging'
      - '!production'

jobs:
  magento2-build:
    if: contains(github.event.pull_request.labels.*.name, 'area:backend') && ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    name: 'm2 tests & build'

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: "⚖️ Start standards testing"
        if: always()
        uses: MAD-I-T/magento-actions@v3.18
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'phpcs-test'
          extension: 'app/code/TestVendor'
          severity: 6
          php: 8.1
          standard: Magento2
          magento_version: 2.4.5
      - run: echo "✅ Standards coding testing finished"

      - name: '☢️ Launch security scanner files'
        if: always()
        uses: MAD-I-T/magento-actions@v3.18
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'security-scan-files'
          elasticsearch: 1
      - run: echo "✅ Security scan files finished"
```
