### ISSUE TITLE
Add testsuite parameter for unit tests

### ISSUE THREAD

**Issue by leoner-omnipro** [MAD-I-T/magento-actions#42]

**Comment by seyuf** [comment]
This will be implemented ASAP.

**Comment by seyuf** [comment]
@leoner-omnipro testsuite param should now be available on @master for testing :
```
    - name: 'launch magento2 unit test filtered by testsuite'
      if: always()
      uses: MAD-I-T/magento-actions@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'unit-test'
        testsuite: 'Magento_Unit_Tests_Other'
        elasticsearch: 1

```

see [example here](https://github.com/seyuf/magento-actions-sample/blob/8d442f07a5037a1631dee3507ddc3ece5a1fdbd1/.github/workflows/main.yml#L55)
