### ISSUE TITLE
Segfault when running ECE Patches Apply

### ISSUE THREAD

**Issue by clivewalkden** [MAD-I-T/magento-actions#59]
Hi,

We've been getting random occurrences of the error below. This is while the build process is running, so it is related to the GitHub infrastructure and memory? Anyone else getting this, and is there a solution?

`/opt/config/utils/apply-composer-patches.sh: line 23:  2092 Segmentation fault      (core dumped) php -d memory_limit=-1 vendor/bin/ece-patches apply`

Kind regards,

Clive

**Comment by seyuf** [comment]
Hi @clivewalkden 
What's your php and magento versions ?

**Comment by seyuf** [comment]
![Image](https://github.com/user-attachments/assets/3653bd16-9f0e-4fff-a9ef-6c88ab4cd935)
Apparently there are some restrictions after tool update. Not sure this is related to your issue though.
In any case, please provide your db version?(or the main.yml content) I'll test this ASAP. Also does the error occur all the time ?

**Comment by clivewalkden** [comment]
@seyuf The build image uses the default MySQL 8.0

<img width="1309" alt="Image" src="https://github.com/user-attachments/assets/8dc2405d-3bbe-4b39-8dc0-2284e41a98dd" />

Is that enough info?

**Comment by seyuf** [comment]
I'm unable to reproduce the issue. Here's the content of my  `.magento.env.yaml`  just some random patches to apply : 
```
stage:
  build:
    QUALITY_PATCHES:
      - MDVA-39305-V3
      - MDVA-19640
      - MDVA-12304
```

Please provide your list of patches  ?

**Comment by seyuf** [comment]
Here's the full main.yml used for the testing : 
```
name: m2-actions-test
on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-22.04
    name: 'm2 tests & build'
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3106:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.1.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      #opensearch:
      #  image: ghcr.io/mad-i-t/magento-opensearch:2.5.0
      #  ports:
      #    - 9100:9200
      #  options: -e="discovery.type=single-node" -e "plugins.security.disabled=true" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
    - uses: actions/checkout@v3


    - name: 'install fresh magento repo'
      if: ${{false}}
      uses: MAD-I-T/magento-actions@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'create-project'
        magento_version: 2.4.7-p2


    - name: 'launch magento2 composer audit'
      if: always()
      id: build
      uses: MAD-I-T/magento-actions@master
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'build'
        apply_patches: 1
   
       
        
```
